AWSTemplateFormatVersion: '2010-09-09'

Description: 'Serverless architecture for the nextJS system'

Parameters:
  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'

  EcsClusterId:
    Type: 'String'

  EcsTaskExecutionRoleId:
    Type: 'String'

  EcsSecGrpId:
    Type: 'String'

  AlbSecGrpId:
    Type: 'String'

  OpenSearchCollection:
    Type: 'String'

  OpenSearchCollectionArn:
    Type: 'String'

  ApolloServerPort:
    Type: 'Number'
    Default: 4000

  NarrativeGeneratorPort:
    Type: 'Number'
    Default: 4030

  AwsFirelensRepositoryUri:
    Type: 'String'

  AwsFirelensImageTag:
    Type: 'String'
    Default: 'latest'

  Env:
    Type: 'String'
    Default: 'dev'

  AppName:
    Type: 'String'

  Domain:
    Type: 'String'

  ContainerName:
    Type: 'String'

  CloudMapNamespaceARN:
    Type: 'String'

  AppPort:
    Type: 'Number'

  EcsDesiredServiceCount:
    Type: 'Number'
    Default: 1

  EcrRepositoryUri:
    Type: 'String'

  EcrImageTag:
    Type: 'String'

  AlbTargetGroupArn:
    Type: 'String'

  CdnDomain:
    Type: 'String'

  JwtSecret:
    Type: 'String'

  CpuSize:
    Type: 'String'
    Default: '2048' # 2 vCPU

  MemorySize:
    Type: 'String'
    Default: '4096' # 4GB

  StartTimeout:
    Type: 'Number'
    Default: 30 # seconds

  HealthCheckGracePeriod:
    Type: 'Number'
    Default: 180 # seconds

  MinimumHealthyContainerPercentage:
    Type: 'Number'
    Default: 50

  MaximumHealthyContainerPercentage:
    Type: 'Number'
    Default: 150

  StopTimeout:
    Type: 'Number'
    Default: 30 # seconds

  LogLevel:
    Type: 'String'
    Default: 'warn'
    AllowedValues:
      - 'debug'
      - 'info'
      - 'warn'
      - 'error'

  HelpdeskEmail:
    Type: 'String'

Conditions:
  IsProd:
    !Equals [!Ref Env, 'prd']

Resources:
  # -----------------------------------------------------------
  # Identitity and Access Management (IAM)
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_IAM.html
  # -----------------------------------------------------------
  # Role that grants our containers in the task permission to call AWS APIs
  EcsTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonRDSDataFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSESFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess'
      Policies:
        - PolicyName: 'nexjs-aoss'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'aoss:APIAccessAll'
                Resource:
                  - !Ref OpenSearchCollectionArn
        - PolicyName: 'nextjs-session-manager'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Effect: 'Allow'
              Action:
                - 'ecs:ExecuteCommand'
                - 'ssmmessages:CreateControlChannel'
                - 'ssmmessages:CreateDataChannel'
                - 'ssmmessages:OpenControlChannel'
                - 'ssmmessages:OpenDataChannel'
              Resource: '*'
              Condition:
                StringEquals:
                  "ecs:container-name": !Ref ContainerName

  # -----------------------------------------------------------
  # Elastic Container Service (ECS) - Containers that host the application
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ECS.html
  # -----------------------------------------------------------
  EcsTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    DependsOn:
      - EcsTaskRole
    Properties:
      Cpu: !Ref CpuSize
      Memory: !Ref MemorySize
      ExecutionRoleArn: !Ref EcsTaskExecutionRoleId
      TaskRoleArn: !GetAtt EcsTaskRole.Arn
      Family: !Sub '${AWS::StackName}-nextjs-server'
      NetworkMode: 'awsvpc' # Required for Fargate!
      RuntimePlatform:
        CpuArchitecture: 'X86_64'
        OperatingSystemFamily: 'LINUX'
      RequiresCompatibilities:
        - 'FARGATE'
      ContainerDefinitions:
        - Image: !Sub "${EcrRepositoryUri}:${EcrImageTag}"
          DisableNetworking: false
          Essential: true
          Interactive: true
          Name: !Ref ContainerName
          StartTimeout: !Ref StartTimeout
          StopTimeout: !Ref StopTimeout
          # HealthCheck:
          #   Command:  ["CMD-SHELL", "curl -f http://127.0.0.1:3000/en-US/login || exit 1"]
          #   Interval: 30
          #   Retries: 3
          #   Timeout: 5
          #   StartPeriod: 60

          LogConfiguration:
            LogDriver: 'awsfirelens'
            Options:
              Name: 'opensearch'
              Host: !Sub '${OpenSearchCollection}.${AWS::Region}.aoss.amazonaws.com'
              Port: 443
              # Index name MUST be lower case!
              Index: !Sub "dmp-log-${Env}-nextjs"
              Aws_Auth: 'On'
              Aws_Region: !Sub '${AWS::Region}'
              Aws_Service_Name: 'aoss'
              Trace_Error: 'On'
              Trace_Output: 'On'
              Suppress_Type_Name: 'On'
              tls: 'On'
              retry_limit: 2
          PortMappings:
            - ContainerPort: !Ref AppPort # ALB port (The port we are listening on)
              Protocol: 'tcp'
              Name: !Sub "nextjs_${AppPort}"
            - ContainerPort: 443
              Protocol: 'tcp'
              Name: "nextjs_443"
            - ContainerPort: '3030' # Service connect port
              Protocol: 'tcp'
              Name: 'nextjs_3030'

          Environment:
            # The application as it should appear in emails and other messaging
            - Name: 'APP_NAME'
              Value: !Ref AppName

            # The logging level you want the application use
            - Name: 'LOG_LEVEL'
              Value: !Ref LogLevel

            # The helpdesk email
            - Name: 'HELPDESK_EMAIL'
              Value: !Ref HelpdeskEmail

            # The NextJS base URL
            - Name: 'NEXT_PUBLIC_BASE_URL'
              Value: !Sub "${Domain}"

            # The NextJS server endpoint
            - Name: 'NEXT_PUBLIC_SERVER_ENDPOINT'
              Value: !Sub "${Domain}"

            # The ApolloServer endpoint for GraphQL queries
            - Name: 'NEXT_PUBLIC_GRAPHQL_SERVER_ENDPOINT'
              Value: !Sub "${Domain}/graphql"

            - Name: "NEXT_PUBLIC_NARRATIVE_ENDPOINT"
              Value: !Sub "http://narrative:${NarrativeGeneratorPort}"

            - Name: 'SERVER_ENDPOINT'
              Value: !Sub "http://apollo:${ApolloServerPort}"

            - Name: "SERVER_LOG_LEVEL"
              Value: !Ref LogLevel

            # CDN endpoint
            - Name: "CDN_ENDPOINT"
              Value: !Sub "cdn.${CdnDomain}"

            # JWT Secret
            - Name: 'JWT_SECRET'
              Value: !Ref JwtSecret

            # The AWS Firelens sidecar container to send application logs to opensearch
            # Firelens sidecar won't redeploy unless this defintion changes
            # Change this value to force a redeploy of the firelens sidecar
            - Name: 'DUMMY_TO_TRIGGER_REDEPLOY_OF_SIDECARS'
              Value: 'v1.1'

        # The AWS Firelens sidecar container to send application logs to opensearch
        - Name: !Sub "${ContainerName}Firelens${Env}"
          Image: !Sub "${AwsFirelensRepositoryUri}:${AwsFirelensImageTag}"
          Cpu: 0
          MemoryReservation: 51
          Essential: true
          User: 0
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Sub "/ecs/firelens-${ContainerName}-${Env}"
              mode: 'non-blocking'
              awslogs-create-group: true
              max-buffer-size: '25m'
              awslogs-region: !Sub '${AWS::Region}'
              awslogs-stream-prefix: 'firelens'
          HealthCheck:
            Command: [ "CMD-SHELL", "pidof fluent-bit >/dev/null || exit 1" ]
            Interval: 30
            Retries: 3
            Timeout: 5
            StartPeriod: 10
          FirelensConfiguration:
            Type: 'fluentbit'
          Environment:
            - Name: 'FLB_LOG_LEVEL'
              Value: 'debug'

  # Container Service definition
  EcsService:
    Type: 'AWS::ECS::Service'
    DependsOn:
      - EcsTaskDefinition
    Properties:
      ServiceName: !Ref AWS::StackName
      Cluster: !Ref EcsClusterId
      DesiredCount: !Ref EcsDesiredServiceCount
      EnableECSManagedTags: true
      EnableExecuteCommand: true # Allow session manager
      HealthCheckGracePeriodSeconds: !Ref HealthCheckGracePeriod
      LaunchType: 'FARGATE'
      DeploymentConfiguration:
        MaximumPercent: !Ref MaximumHealthyContainerPercentage
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        # TODO: Investigate blue/green deployment strategies for prod.
        #       "CODE_DEPLOY" does not allow CF to deploy task changes!
        Type: !If
          - IsProd
          - 'ECS' # 'CODE_DEPLOY'
          - 'ECS'
      LoadBalancers:
        - TargetGroupArn: !Ref AlbTargetGroupArn
          ContainerPort: !Ref AppPort
          ContainerName: !Ref ContainerName
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref EcsSecGrpId
            - !Ref AlbSecGrpId
          AssignPublicIp: 'ENABLED'
          Subnets: !Ref Subnets
      PlatformVersion: 'LATEST'
      PropagateTags: 'TASK_DEFINITION'
      SchedulingStrategy: 'REPLICA'
      TaskDefinition: !Ref EcsTaskDefinition
      ServiceConnectConfiguration:
        Enabled: true
        Namespace: !Ref CloudMapNamespaceARN
        Services:
          - DiscoveryName: 'nextjs'
            PortName: 'nextjs_3030'
            ClientAliases:
              - DnsName: 'nextjs'
                Port: !Ref AppPort

Outputs:
  EcsServiceArn:
    Value: !Ref EcsService

  EcsServiceName:
    Value: !GetAtt EcsService.Name

  EcsTaskId:
    Value: !Ref EcsTaskDefinition

  EcsTaskRoleArn:
    Value: !GetAtt EcsTaskRole.Arn