# In the cdl-uc3-prd account devs must call cloudformation using a service role
cloudformation_service_role:  !ssm
  name: /uc3/prd/CfnServiceRoleArn
  region: us-west-2

# Stack tags are attached to every AWS resource created by these CloudFormation templates
# with the exception of the Lambda functions and layers which are managed by AWS SAM.
stack_tags:
  Program: 'uc3'
  Service: 'dmp'
  Subservice: 'tool'
  Environment: 'stg'
  CodeRepo: 'https://github.com/CDLUC3/dmptool-infrastructure'
  Contact: 'briley'

# Define reusable variables that can be referenced in template specific config files via:
#   my_variable: !stack_attr sceptre_user_data.[variable]
sceptre_user_data:
  # We include the profile here so that we can build resources in any of the AWS regions
  vpc_id: !stack_output_external cdl-uc3-prd-vpc-stack::vpc cdl-uc3-prd

  public_subnets:
    - !stack_output_external cdl-uc3-prd-defaultsubnet-stack::defaultsubnet2a cdl-uc3-prd
    - !stack_output_external cdl-uc3-prd-defaultsubnet-stack::defaultsubnet2b cdl-uc3-prd
    - !stack_output_external cdl-uc3-prd-defaultsubnet-stack::defaultsubnet2c cdl-uc3-prd

  # We sometimes need to access the subnets individually
  public_subnet_a: !stack_output_external cdl-uc3-prd-defaultsubnet-stack::defaultsubnet2a cdl-uc3-prd
  public_subnet_b: !stack_output_external cdl-uc3-prd-defaultsubnet-stack::defaultsubnet2b cdl-uc3-prd
  public_subnet_c: !stack_output_external cdl-uc3-prd-defaultsubnet-stack::defaultsubnet2c cdl-uc3-prd

  # The Hosted Zone
  hosted_zone: !stack_output_external uc3-ops-aws-prd-route53::HostedZoneIdUc3StgCdlibNet cdl-uc3-prd

  # Environment specific variables
  app: 'dmptool'
  env: 'stg'
  domain: 'dmptool-stg.uc3stg.cdlib.net'
  ssm_path: '/uc3/dmp/tool/stg/'

  # ECS container name prefixes
  backend_server_container_name: 'apolloServer'
  frontend_server_container_name: 'nextJS'
  shibboleth_server_container_name: 'shibboleth'
