template:
  path: 'waf.yaml'
  type: 'file'

parameters:
  # Specifies whether this is for a CLOUDFRONT distribution or for a REGIONAL application
  Scope: 'REGIONAL'

  # Whether AWS WAF should store a sampling of the web requests that matched the rules.
  SampledRequestsEnabled: 'true'

  # Whether WAF sends metrics to Amazon CloudWatch.
  CloudWatchMetricsEnabled: 'true'

  # Log bucket for WAF that will be used to send logs to OpenSearch via Fluentbit
  S3WafLogsBucketARN: !stack_output stg/s3.yaml::S3WafLogsBucketARN