AWSTemplateFormatVersion: '2010-09-09'

Description: 'CodeBuild for running database migrations'

Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'

  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'

  Program:
    Type: 'String'

  Service:
    Type: 'String'

  Subservice:
    Type: 'String'

  CodeRepo:
    Type: 'String'

  Contact:
    Type: 'String'

  Env:
    Type: 'String'
    Default: 'dev'

  CodeStarConnectionArn:
    Type: 'String'

  S3ArtifactBucketArn:
    Type: 'String'

  S3ArtifactBucketId:
    Type: 'String'

  RdsSecurityGroupId:
    Type: 'String'

  RdsPort:
    Type: 'String'

  LogRetentionDays:
    Type: 'Number'
    Default: 30

  CodeBuildEnvironmentType:
    Type: 'String'
    Default: 'LINUX_CONTAINER'

  CodeBuildEnvironmentComputeType:
    Type: 'String'
    Default: 'BUILD_GENERAL1_SMALL'

  CodeBuildEnvironmentImage:
    Type: 'String'
    # Default is AL2023
    Default: 'aws/codebuild/amazonlinux2-x86_64-standard:5.0'

  CodeBuildArtifactType:
    Type: 'String'
    Default: 'GITHUB'

  CodeBuildTimeout:
    Type: 'Number'
    Default: 5 # minutes

Resources:
  # ----------------------------------------------------
  # CloudWatch LogGroup
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Logs.html
  # ----------------------------------------------------
  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: !Ref LogRetentionDays

  # -----------------------------------------------------------
  # Identitity and Access Management (IAM)
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_IAM.html
  # -----------------------------------------------------------
  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${AWS::StackName}-Role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'codebuild.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser'
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-build-policy'
          PolicyDocument: !Sub >
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:PutLogEvents",
                    "logs:AssociateKmsKey"
                  ],
                  "Resource": [
                    "${LogGroup.Arn}",
                    "${LogGroup.Arn}:*"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "codebuild:CreateReportGroup",
                    "codebuild:CreateReport",
                    "codebuild:UpdateReport",
                    "codebuild:BatchPutTestCases",
                    "codebuild:BatchPutCodeCoverages"
                  ],
                  "Resource": [
                    "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/*'"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "s3:PutObject",
                    "s3:GetObject",
                    "s3:GetObjectVersion",
                    "s3:GetBucketAcl",
                    "s3:GetBucketLocation",
                    "s3:GetBucketVersioning"
                  ],
                  "Resource": [
                    "${S3ArtifactBucketArn}",
                    "${S3ArtifactBucketArn}/*"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:*",
                    "ec2:CreateNetworkInterface",
                    "ec2:DescribeNetworkInterfaces",
                    "ec2:DeleteNetworkInterface",
                    "ec2:DescribeSubnets",
                    "ec2:DescribeSecurityGroups",
                    "ec2:DescribeDhcpOptions",
                    "ec2:DescribeVpcs",
                    "ec2:CreateNetworkInterfacePermission"
                  ],
                  "Resource": [
                    "*"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": ["ecr:*"],
                  "Resource": [
                    "*"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "codestar-connections:*",
                    "codestar-connections.api:*"
                  ],
                  "Resource": "${CodeStarConnectionArn}"
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "ssm:GetParameters",
                    "ssm:GetParameter"
                  ],
                  "Resource": ["*"]
                }
              ]
            }

  # ---------------------------------------------------------------------------------
  # EC2 Security Groups to let CodeBuild run DB migrations
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
  # ---------------------------------------------------------------------------------
  CodeBuildSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub '${AWS::StackName} CodeBuild Security Group'
      GroupName: !Sub '${AWS::StackName}-SecGrp'
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - Description: 'CodeBuild allow all outbound traffic'
          IpProtocol: '-1'
          FromPort: -1
          ToPort: -1
          CidrIp: '0.0.0.0/0'
      SecurityGroupIngress:
        - Description: 'CodeBuild allow inbound traffic on 443'
          IpProtocol: 'tcp'
          FromPort: 443
          ToPort: 443
          CidrIp: '0.0.0.0/0'
      # Setting our own tags here because we need to include the `ConfigExclude` for this resource
      Tags:
        - Key: 'Program'
          Value: !Ref Program
        - Key: 'Service'
          Value: !Ref Service
        - Key: 'Subservice'
          Value: !Ref Subservice
        - Key: 'Environment'
          Value: !Ref Env
        - Key: 'CodeRepo'
          Value: !Ref CodeRepo
        - Key: 'Contact'
          Value: !Ref Contact
        - Key: 'ConfigExclude'
          Value: 'Security-group-attached-to-ENI'

  # Allow RDS to receive traffic from this CodeBuild
  RdsSecurityGroupIngressFromCodeBuild:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: 'tcp'
      FromPort: !Ref RdsPort
      ToPort: !Ref RdsPort
      GroupId: !Ref RdsSecurityGroupId
      SourceSecurityGroupId: !GetAtt CodeBuildSecurityGroup.GroupId

  # Allow this CodeBuild to receive from RDS
  CodeBuildSecurityGroupIngressFromRds:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: 'tcp'
      FromPort: !Ref RdsPort
      ToPort: !Ref RdsPort
      GroupId: !GetAtt CodeBuildSecurityGroup.GroupId
      SourceSecurityGroupId: !Ref RdsSecurityGroupId

  # -----------------------------------------------------------
  # CodeBuild
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_CodeBuild.html
  # -----------------------------------------------------------
  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${AWS::StackName}-Project'
      QueuedTimeoutInMinutes: 5
      ConcurrentBuildLimit: 1
      Artifacts:
        Type: 'CODEPIPELINE'
        OverrideArtifactName: true
      Cache:
        Type: 'S3'
        Location: !Sub "${S3ArtifactBucketId}/data-migration/build-cache"
      VpcConfig:
        VpcId: !Ref VpcId
        Subnets: !Ref Subnets
        SecurityGroupIds:
          - !GetAtt CodeBuildSecurityGroup.GroupId
      Environment:
        ComputeType: !Ref CodeBuildEnvironmentComputeType
        Image: !Sub "${AWS::AccountId}.${CodeBuildEnvironmentImage}"
        ImagePullCredentialsType: 'SERVICE_ROLE'
        PrivilegedMode: true
        Type: !Ref CodeBuildEnvironmentType
        EnvironmentVariables:
          - Name: 'ENV'
            Value: !Ref Env
      Source:
        Type: 'CODEPIPELINE'
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - echo "Running database migrations"
                - ./data-migrations/process.sh $ENV
                - printf '[{"status":"OK"}]' > dataMigrations.json
          artifacts:
            files:
              - dataMigrations.json
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref LogGroup
          Status: 'ENABLED'
      ServiceRole: !Ref CodeBuildRole
      TimeoutInMinutes: !Ref CodeBuildTimeout

Outputs:
  LogGroupArn:
    Value: !GetAtt LogGroup.Arn

  LogGroupName:
    Value: !Ref LogGroup

  CodeBuildRoleArn:
    Value: !GetAtt CodeBuildRole.Arn

  CodebuildSecurityGroupId:
    Value: !GetAtt CodeBuildSecurityGroup.GroupId

  CodeBuildProjectId:
    Value: !Ref CodeBuildProject

  CodeBuildProjectArn:
    Value: !GetAtt CodeBuildProject.Arn
