template:
  path: 'lambda/layer.yaml'
  type: file

parameters:
  Env: !stack_attr sceptre_user_data.env

  LayerName: 'dynamo'

  S3BucketId: !stack_output dev/s3.yaml::S3PrivateBucketID

  # Do not change this manually, it is updated by the build script
  S3Key: 'lambda/layer/dmptool-dynamo-dev.zip'

hooks:
  before_launch:
    - !cmd "./src/sam-build-and-package-layer.sh dev dynamo ./src/lambda/layer/dynamo"
