template:
  path: 'lambda/layer.yaml'
  type: file

parameters:
  Env: !stack_attr sceptre_user_data.env

  LayerName: 'logger'

  S3BucketId: !stack_output dev/s3.yaml::S3PrivateBucketID

  # Do not change this manually, it is updated by the build script
  S3Key: 'lambda/layer/dmptool-logger-dev-6e70a3e9e129a6a62a2220c31cbb2d354fa811276d9bc6a393cdb3a1ae6db282.zip'

hooks:
  before_launch:
    - !cmd "./src/sam-build-and-package-layer.sh dev logger ./src/lambda/layer/logger"
