template:
  path: 'lambda/layer.yaml'
  type: file

parameters:
  Env: !stack_attr sceptre_user_data.env

  LayerName: 'ssm'

  S3BucketId: !stack_output dev/s3.yaml::S3PrivateBucketID

  # Do not change this manually, it is updated by the build script
  S3Key: 'lambda/layer/dmptool-ssm-dev-4e1915fcd16346505003611f7c818e05194f98cb7c0b48af1401364974976eaa.zip'

hooks:
  before_launch:
    - !cmd "./src/sam-build-and-package-layer.sh dev ssm ./src/lambda/layer/ssm"
