template:
  path: 'codebuild/apollo.yaml'
  type: 'file'

parameters:
  Program: !stack_attr stack_tags.Program
  Service: !stack_attr stack_tags.Service
  Subservice: !stack_attr stack_tags.Subservice
  CodeRepo: !stack_attr stack_tags.CodeRepo
  Contact: !stack_attr stack_tags.Contact

  Env: !stack_attr sceptre_user_data.env

  CodeStarConnectionArn: !stack_output dev/codestar.yaml::CodestarConnectionARN

  EcrRepositoryArn: !stack_output dev/ecr.yaml::EcrRepositoryARN
  EcrRepositoryUri: !stack_output dev/ecr.yaml::EcrRepositoryURI
  EcrRepositoryName: !stack_output dev/ecr.yaml::EcrRepositoryName

  S3ArtifactBucketArn: !stack_output dev/s3.yaml::S3PrivateBucketARN
  S3ArtifactBucketId: !stack_output dev/s3.yaml::S3PrivateBucketID

  LogRetentionDays: '30'

  ContainerName: !stack_attr sceptre_user_data.apollo_container_name

  NodeEnv: 'production'

  CodeBuildEnvironmentType: 'LINUX_CONTAINER'
  CodeBuildEnvironmentComputeType: 'BUILD_GENERAL1_SMALL'
  # This is AL2023. Use `aws codebuild list-curated-environment-images` to see the latest images
  CodeBuildEnvironmentImage: 'aws/codebuild/amazonlinux2-x86_64-standard:5.0'
  CodeBuildTimeout: '15'
