template:
  path: 'codebuild/nextJS.yaml'
  type: 'file'

parameters:
  Env: !stack_attr sceptre_user_data.env

  CodeStarConnectionArn: !stack_output stg/codestar.yaml::CodestarConnectionARN

  EcrRepositoryArn: !stack_output stg/ecr.yaml::EcrRepositoryARN
  EcrRepositoryUri: !stack_output stg/ecr.yaml::EcrRepositoryURI
  EcrRepositoryName: !stack_output stg/ecr.yaml::EcrRepositoryName

  S3ArtifactBucketArn: !stack_output stg/s3.yaml::S3PrivateBucketARN
  S3ArtifactBucketId: !stack_output stg/s3.yaml::S3PrivateBucketID

  LogRetentionDays: '30'

  ContainerName: !stack_attr sceptre_user_data.nextjs_container_port

  NodeEnv: 'production'

  CodeBuildEnvironmentType: 'LINUX_CONTAINER'
  CodeBuildEnvironmentComputeType: 'BUILD_GENERAL1_SMALL'
  # This is AL2023. Use `aws codebuild list-curated-environment-images` to see the latest images
  # CodeBuildEnvironmentImage: 'aws/codebuild/eb-nodejs-6.10.0-amazonlinux-64:4.0.0'
  CodeBuildEnvironmentImage: 'aws/codebuild/amazonlinux2-x86_64-standard:5.0'
  CodeBuildTimeout: '15'
