template:
  path: 'codepipeline/narrative-generator.yaml'
  type: 'file'

parameters:
  CodeStarConnectionArn: !stack_output stg/codestar.yaml::CodestarConnectionARN

  S3ArtifactBucketId: !stack_output stg/s3.yaml::S3PrivateBucketID

  CodeBuildProjectName: !stack_output stg/codebuild/narrative-generator.yaml::CodeBuildProjectId

  DataMigrationBuildProjectName: !stack_output stg/codebuild/data-migration.yaml::CodeBuildProjectId

  EcsCluster: !stack_output stg/ecs/cluster.yaml::EcsFargateClusterId

  EcsServiceName: !stack_output stg/ecs/narrative-generator.yaml::EcsServiceName

  Env: !stack_attr sceptre_user_data.env

  AppName: !stack_attr sceptre_user_data.app

  ContainerName: !stack_attr sceptre_user_data.narrative_generator_name

  RepositoryName: 'CDLUC3/dmptool-narrative-generator'

  BranchToMonitor: 'stage'

  SourceOutputArtifactFormat: 'CODEBUILD_CLONE_REF'
