template:
  path: 'lambda/layer.yaml'
  type: file

parameters:
  Env: !stack_attr sceptre_user_data.env

  LayerName: 's3'

  S3BucketId: !stack_output stg/s3.yaml::S3PrivateBucketID

hooks:
  before_launch:
    - !cmd "./src/sam-build-and-package-layer.sh stg s3 ./src/lambda/layer/s3"
