AWSTemplateFormatVersion: '2010-09-09'

Description: 'Elastic container registry for DMP Tool build images'

Parameters:
  Env:
    Type: 'String'
    Default: 'dev'

  ECRLifecyclePolicyTagPrefix:
    Type: 'String'

Resources:
  # -----------------------------------------------------------
  # Elastic Container Repository (ECR) - Hosts the application's Docker images
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ECR.html
  # -----------------------------------------------------------
  EcrRepository:
    Type: 'AWS::ECR::Repository'
    DeletionPolicy: 'Retain'
    Properties:
      RepositoryName: !Ref AWS::StackName
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: !Sub >
          {
            "rules": [
              {
                "action": {
                  "type": "expire"
                },
                "selection": {
                  "countType": "imageCountMoreThan",
                  "countNumber": 1,
                  "tagStatus": "tagged",
                  "tagPrefixList": [
                    "${ECRLifecyclePolicyTagPrefix}"
                  ]
                },
                "description": "Ensure that we do not have more than 1 tagged version",
                "rulePriority": 1
              },
              {
                "action": {
                  "type": "expire"
                },
                "selection": {
                  "countType": "imageCountMoreThan",
                  "countNumber": 3,
                  "tagStatus": "untagged"
                },
                "description": "Only retain the last 3 versions",
                "rulePriority": 2
              }
            ]
          }

Outputs:
  EcrRepositoryName:
    Value: !Ref EcrRepository

  EcrRepositoryARN:
    Value: !GetAtt EcrRepository.Arn

  EcrURIPrefix:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com"

  EcrRepositoryURI:
    Value: !GetAtt EcrRepository.RepositoryUri
