AWSTemplateFormatVersion: '2010-09-09'

Description: 'S3 bucket to store logs (e.g. access logs for other S3 buckets)'

Parameters:
  LogBucketObjectLifeSpan:
    Type: 'Number'
    Default: 30

Resources:
  LogsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Retain'
    Properties:
      BucketName: !Ref AWS::StackName
      AccessControl: 'Private'
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: !Ref LogBucketObjectLifeSpan
            Status: 'Enabled'

Outputs:
  S3BucketID:
    Value: !Ref LogsBucket

  S3BucketURI:
    Value: !Sub "s3://${LogsBucket}"

  S3BucketARN:
    Value: !GetAtt LogsBucket.Arn
