template:
  path: 'ecs/shibboleth.yaml'
  type: 'file'

parameters:
  Subnets: !stack_attr sceptre_user_data.public_subnets

  Env: !stack_attr sceptre_user_data.env
  AppName: !stack_attr sceptre_user_data.app
  Domain: !stack_attr sceptre_user_data.domain
  ContainerName: !stack_attr sceptre_user_data.shibboleth_container_name

  AppPort: !stack_attr sceptre_user_data.shibboleth_container_port

  EcrRepositoryUri: !stack_output dev/ecr.yaml::EcrRepositoryURI

  EcrImageTag: !stack_attr sceptre_user_data.shibboleth_image_tag

  EcsClusterId: !stack_output dev/ecs/cluster.yaml::EcsFargateClusterId
  EcsTaskExecutionRoleId: !stack_output dev/ecs/cluster.yaml::EcsFargateExecutionRoleId
  EcsSecGrpId: !stack_output dev/ecs/cluster.yaml::EcsFargateSecGrp

  AlbTargetGroupArn: !stack_output dev/alb.yaml::ShibbolethTargetGroupArn
  AlbSecGrpId: !stack_output dev/alb.yaml::AlbSecurityGroupId

  OpenSearchCollection: !stack_attr sceptre_user_data.opensearch_log_collection
  OpenSearchCollectionArn: !stack_attr sceptre_user_data.opensearch_log_collection_arn

  EcsDesiredServiceCount: '1'

  CpuSize: '2048'
  MemorySize: '4096'

  StartTimeout: '30'
  HealthCheckGracePeriod: '30'
  MinimumHealthyContainerPercentage: '50'
  MaximumHealthyContainerPercentage: '200'
  StopTimeout: '30'

  # ENV variables used by the container

hooks:
  # ECS needs a placeholder image to be pushed to ECR for the build to succeed
  before_create:
    - !cmd "./src/make-temp-ecs-docker-image.sh dev shibboleth-latest 5000 shibtest"