template:
  path: 'alb.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  Subnets: !stack_attr sceptre_user_data.public_subnets

  HostedZoneId: !stack_attr sceptre_user_data.hosted_zone

  CertificateArn: !stack_output dev/acm.yaml::CertificateArn

  WafArn: !stack_output dev/waf.yaml::WafArn

  S3LogBucketArn: !stack_output dev/s3.yaml::S3LogsBucketARN
  S3LogBucketId: !stack_output dev/s3.yaml::S3LogsBucketID

  Domain: !stack_attr sceptre_user_data.domain

  ApolloPort: !stack_attr sceptre_user_data.apollo_container_port
  NextJsPort: !stack_attr sceptre_user_data.nextjs_container_port
  ShibbolethPort: !stack_attr sceptre_user_data.shibboleth_container_port
