template:
  path: 'batch.yaml'
  type: 'file'

parameters:
  VpcId: !stack_attr sceptre_user_data.vpc_id
  SubnetId: !stack_attr sceptre_user_data.public_subnet_a
  SecurityGroupID: !ssm /uc3/dmp/tool/dev/BatchSecurityGroupID
  EcrRepositoryName: !stack_output dev/ecr.yaml::EcrRepositoryName
  S3RelatedWorksBucketID: !stack_output dev/s3.yaml::S3RelatedWorksBucketID
