template:
  path: dynamo.yaml
  type: file

parameters:
  Env: !stack_attr sceptre_user_data.env

  # Dynamo settings
  #   See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
  DynamoTableClass: 'STANDARD'
  DynamoEnableContributorInsights: 'true'
  DynamoEnablePointInTimeRecovery: 'true'
  DynamoBillingMode: 'PAY_PER_REQUEST'
