template:
  path: sqs.yaml
  type: file

parameters:
  Env: !stack_attr sceptre_user_data.env

  SsmPath: !stack_attr sceptre_user_data.ssm_path

  MessageRetentionSeconds: '7200' # 2 hours

  DeadLetterRetentionSeconds: '259200' # 3 days

  # Delay to allow underlying Lambdas to scale if necessary
  DelaySeconds: '10'

  # The number of times a message is delivered to the queue before being sent to dead-letter queue
  MaxReceiveCount: '3'
