template:
  path: 'ecs/apollo.yaml'
  type: 'file'

parameters:
  Subnets: !stack_attr sceptre_user_data.public_subnets

  Env: !stack_attr sceptre_user_data.env
  AppName: !stack_attr sceptre_user_data.app
  Domain: !stack_attr sceptre_user_data.domain
  ContainerName: !stack_attr sceptre_user_data.apollo_container_name

  DefaultAffiliationUri: !stack_output stg/ssm.yaml::DefaultAffiliationSsmParameter
  DoiBase: !stack_output stg/ssm.yaml::EzidBaseUrlSsmParameter
  DoiShoulder: !ssm /uc3/dmp/tool/stg/EzidShoulder

  AppPort: !stack_attr sceptre_user_data.apollo_container_port

  EcrRepositoryUri: !stack_output stg/ecr.yaml::EcrRepositoryURI

  EcrImageTag: !stack_attr sceptre_user_data.apollo_image_tag

  EcsClusterId: !stack_output stg/ecs/cluster.yaml::EcsFargateClusterId
  EcsTaskExecutionRoleId: !stack_output stg/ecs/cluster.yaml::EcsFargateExecutionRoleId
  EcsSecGrpId: !stack_output stg/ecs/cluster.yaml::EcsFargateSecGrp

  AlbTargetGroupArn: !stack_output stg/alb.yaml::ApolloServerTargetGroupArn
  AlbSecGrpId: !stack_output stg/alb.yaml::AlbSecurityGroupId

  EcsDesiredServiceCount: '2'

  CpuSize: '2048'
  MemorySize: '4096'

  StartTimeout: '30'
  HealthCheckGracePeriod: '30'
  MinimumHealthyContainerPercentage: '50'
  MaximumHealthyContainerPercentage: '200'
  StopTimeout: '30'

  # ENV variables used by the container
  LogLevel: 'debug'
  NodeEnv: 'staging'

  DynamoTableName: !stack_output stg/dynamo.yaml::DynamoTableName

  DmpHubClientId: !ssm /uc3/dmp/tool/stg/DMPHubClientId
  DmpHubClientSecret: !ssm /uc3/dmp/tool/stg/DMPHubClientSecret

  DmpIdBaseUrl: !ssm /uc3/dmp/tool/stg/EzidBaseUrl
  DmpIdShoulder: !ssm /uc3/dmp/tool/stg/EzidShoulder

  BcryptSaltRounds: '10'
  BcryptHashSecret: !ssm /uc3/dmp/tool/stg/BcryptHashSecret
  HashTokenSecret: !ssm /uc3/dmp/tool/stg/CacheHashSecret

  OpenSearchCollection: !stack_attr sceptre_user_data.opensearch_log_collection
  OpenSearchCollectionArn: !stack_attr sceptre_user_data.opensearch_log_collection_arn

  AwsFirelensRepositoryUri: !stack_output stg/ecr.yaml::AwsFirelensRepositoryURI
  AwsFirelensImageTag: "latest"

  JwtSecret: !ssm /uc3/dmp/tool/stg/JWTSecret
  JwtTtl: '1800000' # 30 minutes (in milliseconds)
  JwtRefreshSecret: !ssm /uc3/dmp/tool/stg/JWTRefreshSecret
  JwtRefreshTtl: '86400000' # 24 hours (in milliseconds)

  CsrfLength: '64'
  CsrfTtl: '3600' # 1 hour (in seconds)

  RestDataSourceCacheTtl: '180' # 2 minutes

  DbConnectionLimit: '5'
  DbHost: !stack_output stg/rds.yaml::DbAddress
  DbPort: !stack_output stg/rds.yaml::DbPort
  DbName: !stack_output stg/rds.yaml::DbName
  DbUsername: !ssm /uc3/dmp/tool/stg/RdsUsername
  DbPassword: !ssm /uc3/dmp/tool/stg/RdsPassword

  CacheHost: !stack_output stg/cache.yaml::CachePrimaryEndpointAddress
  CachePort: !stack_output stg/cache.yaml::CachePrimaryEndpointPort
  CacheConnectTimeout: '10000' # 10 seconds

  SesEndpoint: !ssm /uc3/stg/SesEndpoint
  SesBouncedEmailBucket: !ssm /uc3/stg/SesBouncedEmailBucket
  SesAccessKeyId: !ssm /uc3/dmp/tool/stg/SesAccessKeyId
  SesAccessKeySecret: !ssm /uc3/dmp/tool/stg/SesAccessKeySecret

  DoNotReplyEmail: !ssm /uc3/dmp/tool/stg/DoNotReplyEmail
  HelpdeskEmail: !ssm /uc3/dmp/tool/stg/HelpdeskEmail

  UseMockData: 'false'

hooks:
  # ECS needs a placeholder image to be pushed to ECR for the build to succeed
  before_create:
    - !cmd "./src/make-temp-ecs-docker-image.sh stg apollo-latest 4000 up"